#!/bin/bash

if ! [ -x "$(command -v $EDITOR)" ]; then
  echo 'Error: $EDITOR is not set.' >&2
  exit 1
fi

if ! [ -x "$(command -v xsel)" ]; then
  echo 'Error: xsel is not available.' >&2
  exit 1
fi

TMP=$(mktemp -p /tmp -t vimclip.XXXXXXXX)
$EDITOR $TMP
xsel -i -b < $TMP
